apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-tickets-pod
  template:
    metadata:
      labels:
        app: ticketing-tickets-pod
    spec:
      containers:
        - name: ticketing-tickets-cont
          image: sarathinanavati/ticketing-tickets
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: mongodb://ticketing-tickets-mongo-srv:27019/tickets
            - name: JWT_SECRET_KEY # env parameter that will be created in container environment
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # kubectl generic key name
                  key: jwt_key # kubectl key name
            - name: NATS_URL
              value: "http://ticketing-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing-cluster-id
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-tickets-srv
spec:
  selector:
    app: ticketing-tickets-pod
  ports:
    - name: ticketing-tickets
      protocol: TCP
      port: 3300
      targetPort: 3000
